name: EpicFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 5.3
description: Plugin for the Triple Freedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [Madgeek1450, DarthSalamon, cldoesmc, Flamingdragon23]

# plugin.yml is no longer used to define commands.
